// <auto-generated />
using System;
using LucidAdmin.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LucidAdmin.Infrastructure.Migrations
{
    [DbContext(typeof(LucidDbContext))]
    [Migration("20260210083705_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LucidAdmin.Core.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentGroup")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("HostName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LlmServiceAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServiceNowAccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkflowDefinitionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HostName");

                    b.HasIndex("LlmServiceAccountId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ServiceNowAccountId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowDefinitionId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.AgentServiceAccountBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Qualifier")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServiceAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceAccountId");

                    b.HasIndex("AgentId", "Role", "Qualifier")
                        .IsUnique();

                    b.ToTable("AgentServiceAccountBindings", (string)null);
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedServiceAccountIds")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpRestrictions")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUsedFromIp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ToolServerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("IsActive");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("KeyPrefix");

                    b.HasIndex("ToolServerId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.ApprovalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AutoApproveThreshold")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposedAction")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeAfterStep")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketShortDescription")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimeoutMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasAutoApproved")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("WorkflowDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TicketId");

                    b.HasIndex("WorkflowDefinitionId");

                    b.HasIndex("AgentName", "Status");

                    b.ToTable("ApprovalRequests");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetResource")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ToolServerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("AgentId");

                    b.HasIndex("CapabilityId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ToolServerId");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.Capability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationExample")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationSchema")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DependenciesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentationUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinToolServerVersion")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredProvidersJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresServiceAccount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CapabilityId")
                        .IsUnique();

                    b.HasIndex("Category");

                    b.ToTable("Capabilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000001"),
                            CapabilityId = "ad-password-reset",
                            Category = "active-directory",
                            CreatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Description = "Reset Active Directory user passwords with validation",
                            DisplayName = "Reset user passwords in Active Directory",
                            IsBuiltIn = true,
                            IsEnabled = true,
                            RequiredProvidersJson = "[\"windows-ad\"]",
                            RequiresServiceAccount = true,
                            UpdatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Version = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0000-0000-000000000001"),
                            CapabilityId = "ad-group-add",
                            Category = "active-directory",
                            CreatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Description = "Add a user to an Active Directory security or distribution group",
                            DisplayName = "Add user to Active Directory group",
                            IsBuiltIn = true,
                            IsEnabled = true,
                            RequiredProvidersJson = "[\"windows-ad\"]",
                            RequiresServiceAccount = true,
                            UpdatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Version = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0003-0000-0000-000000000001"),
                            CapabilityId = "ad-group-remove",
                            Category = "active-directory",
                            CreatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Description = "Remove a user from an Active Directory security or distribution group",
                            DisplayName = "Remove user from Active Directory group",
                            IsBuiltIn = true,
                            IsEnabled = true,
                            RequiredProvidersJson = "[\"windows-ad\"]",
                            RequiresServiceAccount = true,
                            UpdatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Version = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0004-0000-0000-000000000001"),
                            CapabilityId = "ad-user-lookup",
                            Category = "active-directory",
                            CreatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Description = "Query Active Directory for user information and attributes",
                            DisplayName = "Look up user information in Active Directory",
                            IsBuiltIn = true,
                            IsEnabled = true,
                            RequiredProvidersJson = "[\"windows-ad\"]",
                            RequiresServiceAccount = true,
                            UpdatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Version = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0005-0000-0000-000000000001"),
                            CapabilityId = "ad-user-unlock",
                            Category = "active-directory",
                            CreatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Description = "Unlock a locked Active Directory user account",
                            DisplayName = "Unlock a locked Active Directory account",
                            IsBuiltIn = true,
                            IsEnabled = true,
                            RequiredProvidersJson = "[\"windows-ad\"]",
                            RequiresServiceAccount = true,
                            UpdatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Version = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0006-0000-0000-000000000001"),
                            CapabilityId = "ntfs-permission-grant",
                            Category = "file-system",
                            CreatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Description = "Grant NTFS permissions to users or groups for files and folders",
                            DisplayName = "Grant NTFS file/folder permissions",
                            IsBuiltIn = true,
                            IsEnabled = true,
                            RequiredProvidersJson = "[\"windows-ad\"]",
                            RequiresServiceAccount = true,
                            UpdatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Version = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0007-0000-0000-000000000001"),
                            CapabilityId = "ntfs-permission-revoke",
                            Category = "file-system",
                            CreatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Description = "Revoke NTFS permissions from users or groups for files and folders",
                            DisplayName = "Revoke NTFS file/folder permissions",
                            IsBuiltIn = true,
                            IsEnabled = true,
                            RequiredProvidersJson = "[\"windows-ad\"]",
                            RequiresServiceAccount = true,
                            UpdatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Version = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0008-0000-0000-000000000001"),
                            CapabilityId = "azure-user-lookup",
                            Category = "azure",
                            CreatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Description = "Query Microsoft Entra ID for user details via Microsoft Graph API",
                            DisplayName = "Look up user in Azure AD / Entra ID",
                            IsBuiltIn = true,
                            IsEnabled = true,
                            RequiredProvidersJson = "[\"azure\"]",
                            RequiresServiceAccount = true,
                            UpdatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Version = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0009-0000-0000-000000000001"),
                            CapabilityId = "azure-vm-lookup",
                            Category = "azure",
                            CreatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Description = "Query Azure Resource Manager for VM details including status, size, and IPs",
                            DisplayName = "Look up virtual machine in Azure",
                            IsBuiltIn = true,
                            IsEnabled = true,
                            RequiredProvidersJson = "[\"azure\"]",
                            RequiresServiceAccount = true,
                            UpdatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Version = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0010-0000-0000-000000000001"),
                            CapabilityId = "ad-computer-lookup",
                            Category = "active-directory",
                            CreatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Description = "Query Active Directory for computer objects assigned to a user via managedBy attribute",
                            DisplayName = "Look up user's assigned computer(s)",
                            IsBuiltIn = true,
                            IsEnabled = true,
                            RequiredProvidersJson = "[\"windows-ad\"]",
                            RequiresServiceAccount = true,
                            UpdatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Version = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0011-0000-0000-000000000001"),
                            CapabilityId = "remote-software-install",
                            Category = "workstation-management",
                            CreatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Description = "Install software packages on remote Windows computers via PowerShell Remoting (WinRM)",
                            DisplayName = "Install software on remote computer",
                            IsBuiltIn = true,
                            IsEnabled = true,
                            RequiredProvidersJson = "[\"windows-ad\"]",
                            RequiresServiceAccount = true,
                            UpdatedAt = new DateTime(2026, 2, 10, 8, 37, 5, 600, DateTimeKind.Utc).AddTicks(5323),
                            Version = "1.0.0"
                        });
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.CapabilityMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedScopesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityVersion")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeniedScopesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHealthCheck")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastHealthMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServiceAccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ToolServerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CapabilityId");

                    b.HasIndex("ToolServerId");

                    b.HasIndex("ServiceAccountId", "ToolServerId", "CapabilityId")
                        .IsUnique();

                    b.ToTable("CapabilityMappings");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.Clarification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeAfterStep")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketSysId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserReply")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("AgentName", "Status");

                    b.ToTable("Clarifications", (string)null);
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.Example", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CallerName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExampleSetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedAffectedUser")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedConfidence")
                        .HasPrecision(3, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedEscalationReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedPermissionLevel")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExpectedShouldEscalate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpectedTargetGroup")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedTargetResource")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TicketCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TicketCategoryId");

                    b.HasIndex("ExampleSetId", "Name")
                        .IsUnique();

                    b.ToTable("Examples");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.ExampleSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TicketCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TicketCategoryId");

                    b.ToTable("ExampleSets");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.ManualSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraDataJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Requester")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultDetailsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultStatus")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedAt");

                    b.HasIndex("AgentId", "Status");

                    b.ToTable("ManualSubmissions");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleText")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RulesetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Priority");

                    b.HasIndex("RulesetId");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.Ruleset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsBuiltIn");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Rulesets");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.ServiceAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CredentialNonce")
                        .HasColumnType("BLOB");

                    b.Property<string>("CredentialReference")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialStorage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CredentialsUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedCredentials")
                        .HasColumnType("BLOB");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHealthCheck")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastHealthMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Provider");

                    b.ToTable("ServiceAccounts");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.StepRulesetMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RulesetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowStepId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId");

                    b.HasIndex("WorkflowStepId", "RulesetId")
                        .IsUnique();

                    b.ToTable("StepRulesetMappings");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.StepTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FromStepId")
                        .HasColumnType("TEXT");

                    b.Property<int>("InputIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ToStepId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ToStepId");

                    b.HasIndex("FromStepId", "ToStepId", "OutputIndex")
                        .IsUnique();

                    b.ToTable("StepTransitions");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.TicketCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TicketCategories");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.ToolServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeyHash")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ToolServers");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthenticationSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExampleSetId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LayoutJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerConfigJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExampleSetId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WorkflowDefinitions");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.WorkflowRulesetMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RulesetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId");

                    b.HasIndex("WorkflowDefinitionId", "RulesetId")
                        .IsUnique();

                    b.ToTable("WorkflowRulesetMappings");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DrawflowNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId", "Name")
                        .IsUnique();

                    b.ToTable("WorkflowSteps");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.Agent", b =>
                {
                    b.HasOne("LucidAdmin.Core.Entities.ServiceAccount", "LlmServiceAccount")
                        .WithMany()
                        .HasForeignKey("LlmServiceAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LucidAdmin.Core.Entities.ServiceAccount", "ServiceNowAccount")
                        .WithMany()
                        .HasForeignKey("ServiceNowAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LucidAdmin.Core.Entities.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LlmServiceAccount");

                    b.Navigation("ServiceNowAccount");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.AgentServiceAccountBinding", b =>
                {
                    b.HasOne("LucidAdmin.Core.Entities.Agent", "Agent")
                        .WithMany("ServiceAccountBindings")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LucidAdmin.Core.Entities.ServiceAccount", "ServiceAccount")
                        .WithMany()
                        .HasForeignKey("ServiceAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("ServiceAccount");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.ApiKey", b =>
                {
                    b.HasOne("LucidAdmin.Core.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LucidAdmin.Core.Entities.ToolServer", "ToolServer")
                        .WithMany()
                        .HasForeignKey("ToolServerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");

                    b.Navigation("ToolServer");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.ApprovalRequest", b =>
                {
                    b.HasOne("LucidAdmin.Core.Entities.WorkflowDefinition", null)
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.AuditEvent", b =>
                {
                    b.HasOne("LucidAdmin.Core.Entities.Agent", "Agent")
                        .WithMany("AuditEvents")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LucidAdmin.Core.Entities.ToolServer", "ToolServer")
                        .WithMany("AuditEvents")
                        .HasForeignKey("ToolServerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");

                    b.Navigation("ToolServer");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.CapabilityMapping", b =>
                {
                    b.HasOne("LucidAdmin.Core.Entities.Capability", "Capability")
                        .WithMany("Mappings")
                        .HasForeignKey("CapabilityId")
                        .HasPrincipalKey("CapabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LucidAdmin.Core.Entities.ServiceAccount", "ServiceAccount")
                        .WithMany("CapabilityMappings")
                        .HasForeignKey("ServiceAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LucidAdmin.Core.Entities.ToolServer", "ToolServer")
                        .WithMany("CapabilityMappings")
                        .HasForeignKey("ToolServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capability");

                    b.Navigation("ServiceAccount");

                    b.Navigation("ToolServer");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.Example", b =>
                {
                    b.HasOne("LucidAdmin.Core.Entities.ExampleSet", "ExampleSet")
                        .WithMany("Examples")
                        .HasForeignKey("ExampleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LucidAdmin.Core.Entities.TicketCategory", "TicketCategory")
                        .WithMany("Examples")
                        .HasForeignKey("TicketCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExampleSet");

                    b.Navigation("TicketCategory");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.ExampleSet", b =>
                {
                    b.HasOne("LucidAdmin.Core.Entities.TicketCategory", "TicketCategory")
                        .WithMany("ExampleSets")
                        .HasForeignKey("TicketCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TicketCategory");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.ManualSubmission", b =>
                {
                    b.HasOne("LucidAdmin.Core.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.Rule", b =>
                {
                    b.HasOne("LucidAdmin.Core.Entities.Ruleset", "Ruleset")
                        .WithMany("Rules")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.StepRulesetMapping", b =>
                {
                    b.HasOne("LucidAdmin.Core.Entities.Ruleset", "Ruleset")
                        .WithMany()
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LucidAdmin.Core.Entities.WorkflowStep", "WorkflowStep")
                        .WithMany("RulesetMappings")
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruleset");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.StepTransition", b =>
                {
                    b.HasOne("LucidAdmin.Core.Entities.WorkflowStep", "FromStep")
                        .WithMany("OutgoingTransitions")
                        .HasForeignKey("FromStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LucidAdmin.Core.Entities.WorkflowStep", "ToStep")
                        .WithMany("IncomingTransitions")
                        .HasForeignKey("ToStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromStep");

                    b.Navigation("ToStep");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.WorkflowDefinition", b =>
                {
                    b.HasOne("LucidAdmin.Core.Entities.ExampleSet", "ExampleSet")
                        .WithMany()
                        .HasForeignKey("ExampleSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExampleSet");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.WorkflowRulesetMapping", b =>
                {
                    b.HasOne("LucidAdmin.Core.Entities.Ruleset", "Ruleset")
                        .WithMany()
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LucidAdmin.Core.Entities.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("RulesetMappings")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruleset");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.WorkflowStep", b =>
                {
                    b.HasOne("LucidAdmin.Core.Entities.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.Agent", b =>
                {
                    b.Navigation("AuditEvents");

                    b.Navigation("ServiceAccountBindings");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.Capability", b =>
                {
                    b.Navigation("Mappings");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.ExampleSet", b =>
                {
                    b.Navigation("Examples");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.Ruleset", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.ServiceAccount", b =>
                {
                    b.Navigation("CapabilityMappings");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.TicketCategory", b =>
                {
                    b.Navigation("ExampleSets");

                    b.Navigation("Examples");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.ToolServer", b =>
                {
                    b.Navigation("AuditEvents");

                    b.Navigation("CapabilityMappings");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.WorkflowDefinition", b =>
                {
                    b.Navigation("RulesetMappings");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("LucidAdmin.Core.Entities.WorkflowStep", b =>
                {
                    b.Navigation("IncomingTransitions");

                    b.Navigation("OutgoingTransitions");

                    b.Navigation("RulesetMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
