#!/bin/bash
set -e

# ─────────────────────────────────────────────────────────────────
# Praxova Admin Portal — Container Entrypoint
# ─────────────────────────────────────────────────────────────────
# Installs the Praxova internal CA into the OS trust store BEFORE
# the .NET runtime starts. This is critical because OpenSSL caches
# the trust store at process initialization — any CA added after
# dotnet starts will not be seen by HttpClient.
#
# On first boot: CA doesn't exist yet (generated by .NET at startup).
#   The Blazor HttpClient factory handles this via explicit chain
#   validation as a fallback.
# On subsequent boots: CA exists on the persistent volume from the
#   previous run and is installed here before .NET launches.
# ─────────────────────────────────────────────────────────────────

CA_SOURCE="/app/data/certs/ca.pem"
CA_TARGET="/usr/local/share/ca-certificates/praxova-internal-ca.crt"

if [ -f "$CA_SOURCE" ]; then
    cp "$CA_SOURCE" "$CA_TARGET"
    update-ca-certificates --fresh > /dev/null 2>&1 || true
    echo "[entrypoint] Praxova CA installed in OS trust store"
else
    echo "[entrypoint] No existing CA found — will be generated at startup"
fi

# Hand off to the .NET application
exec dotnet LucidAdmin.Web.dll "$@"
