#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────
# Praxova Docker Bootstrap Script
# Runs on the remote Docker host after containers are deployed.
#
# Sources /tmp/praxova-bootstrap.env for configuration (written
# by the Tofu file provisioner before this script is uploaded).
#
# Sequence:
#   1. Wait for portal health
#   2. Pull Ollama model
#   3. Authenticate → JWT
#   4. Ensure agent entity exists (create if 404)
#   5. Create API key for agent
#   6. Write API key to /opt/praxova/.env
#   7. Restart agent container
#   8. Verify all containers running
#   9. Cleanup sensitive config file
# ─────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Load config written by Tofu ──────────────────────────────────
ENV_CONFIG="/tmp/praxova-bootstrap.env"
if [[ ! -f "$ENV_CONFIG" ]]; then
  echo "ERROR: Missing bootstrap config at $ENV_CONFIG"
  exit 1
fi
# shellcheck source=/dev/null
source "$ENV_CONFIG"

# ── Helpers ─────────────────────────────────────────────────────
log() { echo "[$(date '+%H:%M:%S')] $*"; }

require_cmd() {
  command -v "$1" > /dev/null 2>&1 || {
    log "ERROR: Required command '$1' not found"
    exit 1
  }
}

require_cmd curl
require_cmd jq
require_cmd docker

log "═══════════════════════════════════════════════════════════════"
log "  Praxova Bootstrap"
log "  Agent : ${AGENT_NAME}"
log "  Model : ${OLLAMA_MODEL}"
log "  Stack : ${STACK_DIR}"
log "═══════════════════════════════════════════════════════════════"

# ── Step 1: Wait for portal health ──────────────────────────────
log "Waiting for admin portal..."
ATTEMPTS=30
for i in $(seq 1 $ATTEMPTS); do
  if curl -sf "${PORTAL_HTTP_URL}/api/health/" > /dev/null 2>&1; then
    log "Portal healthy (attempt ${i}/${ATTEMPTS})"
    break
  fi
  if [[ $i -eq $ATTEMPTS ]]; then
    log "ERROR: Portal did not become healthy after $((ATTEMPTS * 10))s"
    log "Check: cd ${STACK_DIR} && docker compose logs admin-portal"
    exit 1
  fi
  log "  Not ready yet... (${i}/${ATTEMPTS}, retrying in 10s)"
  sleep 10
done

# ── Step 2: Pull Ollama model ────────────────────────────────────
log "Pulling Ollama model: ${OLLAMA_MODEL}"
log "  (First pull downloads several GB — this may take a while)"
cd "${STACK_DIR}"
if docker compose exec -T ollama ollama list 2>/dev/null | grep -q "^${OLLAMA_MODEL}"; then
  log "  Model already present, skipping pull"
else
  docker compose exec -T ollama ollama pull "${OLLAMA_MODEL}"
  log "  Model pull complete"
fi

# ── Step 3: Authenticate → JWT ───────────────────────────────────
log "Authenticating to portal as '${PORTAL_ADMIN_USER}'..."
AUTH_RESPONSE=$(curl -sf "${PORTAL_HTTP_URL}/api/auth/login" \
  -H "Content-Type: application/json" \
  -d "{\"username\":\"${PORTAL_ADMIN_USER}\",\"password\":\"${PORTAL_ADMIN_PASS}\"}" \
  2>&1) || {
  log "ERROR: Auth request failed. Portal may not be reachable or credentials are wrong."
  exit 1
}

TOKEN=$(echo "$AUTH_RESPONSE" | jq -r '.token // empty')
if [[ -z "$TOKEN" ]]; then
  log "ERROR: No token in auth response. Wrong password?"
  log "Response: $AUTH_RESPONSE"
  exit 1
fi
log "  Authentication successful"

# ── Step 4: Ensure agent entity exists ──────────────────────────
log "Looking up agent '${AGENT_NAME}' in portal..."
AGENT_RESPONSE=$(curl -sf "${PORTAL_HTTP_URL}/api/agents/name/${AGENT_NAME}" \
  -H "Authorization: Bearer ${TOKEN}" 2>&1)
AGENT_HTTP_STATUS=$?

AGENT_ID=$(echo "$AGENT_RESPONSE" | jq -r '.id // empty' 2>/dev/null)

if [[ -n "$AGENT_ID" ]]; then
  log "  Agent found: ${AGENT_ID}"
else
  log "  Agent not found — creating '${AGENT_NAME}'..."
  CREATE_RESPONSE=$(curl -sf "${PORTAL_HTTP_URL}/api/agents" \
    -H "Authorization: Bearer ${TOKEN}" \
    -H "Content-Type: application/json" \
    -d "{
          \"name\": \"${AGENT_NAME}\",
          \"displayName\": \"${AGENT_DISPLAY_NAME}\",
          \"description\": \"Auto-created by Praxova bootstrap\"
        }" 2>&1) || {
    log "ERROR: Agent creation request failed"
    log "Response: $CREATE_RESPONSE"
    exit 1
  }

  AGENT_ID=$(echo "$CREATE_RESPONSE" | jq -r '.id // empty')
  if [[ -z "$AGENT_ID" ]]; then
    log "ERROR: Agent creation response missing ID"
    log "Response: $CREATE_RESPONSE"
    exit 1
  fi
  log "  Agent created: ${AGENT_ID}"
fi

# ── Step 5: Create API key ───────────────────────────────────────
log "Creating API key for agent '${AGENT_NAME}'..."
KEY_RESPONSE=$(curl -sf \
  -X POST "${PORTAL_HTTP_URL}/api/v1/api-keys/agent/${AGENT_ID}" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "Content-Type: application/json" \
  -d "{
        \"name\": \"bootstrap-$(date +%Y%m%d)\",
        \"description\": \"Auto-generated by Praxova bootstrap script\"
      }" 2>&1) || {
  log "ERROR: API key creation request failed"
  log "Response: $KEY_RESPONSE"
  exit 1
}

LUCID_API_KEY=$(echo "$KEY_RESPONSE" | jq -r '.plaintextKey // empty')
if [[ -z "$LUCID_API_KEY" ]]; then
  log "ERROR: API key response missing plaintextKey"
  log "Response: $KEY_RESPONSE"
  exit 1
fi

KEY_PREFIX=$(echo "$KEY_RESPONSE" | jq -r '.key.keyPrefix // "???"')
log "  Key created (prefix: ${KEY_PREFIX})"
log "  This is the only time the full key will be available."

# ── Step 6: Write API key to .env ───────────────────────────────
ENV_FILE="${STACK_DIR}/.env"
log "Writing LUCID_API_KEY to ${ENV_FILE}..."

if [[ ! -f "$ENV_FILE" ]]; then
  log "ERROR: .env not found at ${ENV_FILE}"
  log "Was the stack deployed? Run scripts/deploy-containers.sh first."
  exit 1
fi

# Remove any existing LUCID_API_KEY line, then append the new one.
# Handles both first-run (no key) and re-bootstrap (stale key) cases.
if grep -q "^LUCID_API_KEY=" "$ENV_FILE" 2>/dev/null; then
  sed -i "s|^LUCID_API_KEY=.*|LUCID_API_KEY=${LUCID_API_KEY}|" "$ENV_FILE"
  log "  Updated existing LUCID_API_KEY entry"
else
  echo "LUCID_API_KEY=${LUCID_API_KEY}" >> "$ENV_FILE"
  log "  Appended LUCID_API_KEY to .env"
fi

# ── Step 7: Restart agent container ─────────────────────────────
log "Restarting agent container to pick up new key..."
cd "${STACK_DIR}"
docker compose restart agent-helpdesk-01
log "  Agent restarted"

# Give it a moment to come up before the health check
sleep 5

# ── Step 8: Verify stack health ──────────────────────────────────
log "Verifying container stack..."
UNHEALTHY=0
while IFS= read -r line; do
  # docker compose ps --format table emits:
  #   NAME   IMAGE   COMMAND   SERVICE   STATUS   PORTS
  STATUS=$(echo "$line" | awk '{print $5}')
  NAME=$(echo "$line" | awk '{print $1}')
  if [[ "$STATUS" != "Up" && "$STATUS" != "running" && ! "$STATUS" =~ ^Up ]]; then
    log "  WARNING: ${NAME} — status: ${STATUS}"
    UNHEALTHY=$((UNHEALTHY + 1))
  else
    log "  OK: ${NAME} (${STATUS})"
  fi
done < <(docker compose ps --format table 2>/dev/null | tail -n +2)

if [[ $UNHEALTHY -gt 0 ]]; then
  log "WARNING: ${UNHEALTHY} container(s) not in expected state."
  log "Check: cd ${STACK_DIR} && docker compose logs"
else
  log "All containers healthy"
fi

# ── Step 9: Cleanup ──────────────────────────────────────────────
log "Cleaning up sensitive bootstrap config..."
rm -f /tmp/praxova-bootstrap.env
rm -f /tmp/praxova-bootstrap.sh

log "═══════════════════════════════════════════════════════════════"
log "  Bootstrap complete!"
log ""
log "  Agent   : ${AGENT_NAME} (${AGENT_ID})"
log "  Key     : ${KEY_PREFIX}..."
log "  Stack   : ${STACK_DIR}"
log ""
log "  Portal  : http://${PORTAL_HTTP_URL#http://}"
log "═══════════════════════════════════════════════════════════════"
